"use client";
import React, { useEffect } from "react";
import { useCookieConsent } from "@/app/context/CookieConsentContext";

const Voiceflow = () => {
  const { consent } = useCookieConsent();

  useEffect(() => {
    if (!consent.marketing) return;

    // create script exactly like original <script> snippet
    const script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://cdn.voiceflow.com/widget-next/bundle.mjs";

    script.onload = () => {
      if (!window.voiceflow) return;

      window.voiceflow.chat.load({
        verify: { projectID: "66fd9286a5b369f00abef5fb" },
        url: "https://general-runtime.voiceflow.com",
        versionID: "production",
        voice: {
          url: "https://runtime-api.voiceflow.com",
        },
      });
    };

    // inject script before first <script> tag like original snippet
    const firstScript = document.getElementsByTagName("script")[0];
    firstScript?.parentNode?.insertBefore(script, firstScript);

    return () => {
      // remove script on cleanup
      const loadedScript = document.querySelector(
        'script[src="https://cdn.voiceflow.com/widget-next/bundle.mjs"]'
      );
      if (loadedScript) loadedScript.remove();

      // remove widget container generated by Voiceflow
      const chatContainer = document.getElementById("voiceflow-chat");
      if (chatContainer) chatContainer.remove();

      // remove the floating bubble if exists
      const bubble = document.querySelector('[id^="vf-"]');
      if (bubble) bubble.remove();
    };
  }, [consent.marketing]);

  if (!consent.marketing) return null;

  return <div id="voiceflow-chat" />;
};

export default Voiceflow;


// Add custom styles to position chat widget higher
// const styleSheet = document.createElement("style");
// styleSheet.textContent = `
//   #voiceflow-chat {
//     bottom: 100px !important;
//   }
// `;