import { Portfolio } from "@/types/portfolio";

const WebsitesData: Portfolio[] = [
    {
        _id: 10,
        mainImage: "/images/portfolio/machtrans-full.png",
        title: "Machtrans.pl",
        metadata: "Top SEO and ultra-fast Website in React.js for Transport Company",
        urlLink: "https://machtrans.pl/",
        tags: ["web"],
    },
    {
        _id: 15,
        mainImage: "/images/portfolio/pgr-full.png",
        title: "Pgr-elektroteam.pl",
        metadata: "Website for smart home company",
        urlLink: "/portfolio/elektroteam",
        tags: ["web"],
    },
    {
        _id: 16,
        mainImage: "/images/portfolio/volton.jpg",
        title: "Volton-install.pl",
        metadata: "Business website for electrical services and smart home",
        urlLink: "/portfolio/volton",
        tags: ["web"],
    },
    {
        _id: 18,
        mainImage: "/images/portfolio/klicious-full.png",
        title: "K-licious.pl",
        metadata: "Website and Ecom for Creative Company",
        urlLink: "/portfolio/klicious",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 25,
        mainImage: "/images/portfolio/skin.jpg",
        title: "Skinproject.pl",
        metadata: "Website for Aesthetic Medicine Office",
        urlLink: "/portfolio/skinproject",
        tags: ["web"],
    },
    {
        _id: 26,
        mainImage: "/images/portfolio/slovlydeskop.jpg",
        title: "Slovlystudio.pl",
        metadata: "Online store for handmade clothing brand",
        urlLink: "/portfolio/slovly",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 28,
        mainImage: "/images/portfolio/bakaliovelove.jpg",
        title: "Bakaliowelove.pl",
        metadata: "Woocommerce Store with healthy food",
        urlLink: "/portfolio/bakaliowelove",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 29,
        mainImage: "/images/portfolio/paintball.jpg",
        title: "paintball-osada.pl",
        metadata: "Business website for Entertainment Park and Paintball",
        urlLink: "/portfolio/paintball-osada",
        tags: ["web"],
    },
    {
        _id: 30,
        mainImage: "/images/portfolio/smp.jpg",
        title: "smpolaniec.com.pl",
        metadata: "Website for housing cooperative",
        urlLink: "/portfolio/smpolaniec",
        tags: ["web"],
    },
    {
        _id: 24,
        mainImage: "/images/portfolio/cora.jpg",
        title: "Cora-goralczyk.pl",
        metadata: "Website for automotive mechanic workshop",
        urlLink: "/portfolio/cora-goralczyk",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 22,
        mainImage: "/images/portfolio/bodymedica.jpg",
        title: "bodymedica.pl",
        metadata: "Business website for Physiotherapy Office",
        urlLink: "/portfolio/bodymedica",
        tags: ["web"],
    },
    {
        _id: 21,
        mainImage: "/images/portfolio/lanelyya.jpg",
        title: "Lanelyya.de",
        metadata: "Shop in multiple languages on Shopify for German market",
        urlLink: "/portfolio/lanelyya",
        tags: ["web", "ecommerce"],
    },
];

export default WebsitesData;
