import { Portfolio } from "@/types/portfolio";
import { useTranslation } from 'react-i18next';

const WebsitesData: Portfolio[] = [
    {
        _id: 1,
        mainImage: "/images/portfolio/ainsiderstorenew.png",
        title: "Ainsider.store - AI Tools and Prompts Directory",
        metadata: "A comprehensive directory for discovering the best AI tools and high-quality prompts to optimize your workflows.",
        urlLink: "https://ainsider.store",
        tags: ["web", "apps", "ai", "featured"],
    },
    {
        _id: 2,
        mainImage: "/images/portfolio/machtrans-full.png",
        title: "MachTrans.pl - Transport Company",
        metadata: "Responsive corporate website with full CMS integration and optimized performance.",
        urlLink: "https://machtrans.pl/",
        tags: ["web"],
    },
    {
        _id: 3,
        mainImage: "/images/portfolio/promptgallery.png",
        title: "Promptr Gallery - AI Art Prompts Directory",
        metadata: "An interactive gallery of AI art prompts with a unique feature to customize and refine them for your own creative projects.",
        urlLink: "https://gallery.ainsider.co",
        tags: ["web", "apps", "ai", "featured"],
    },
    {
        _id: 4,
        mainImage: "/images/portfolio/pgr-full.png",
        title: "PGR-Elektroteam.pl - Electrical Services",
        metadata: "Professional business website with project portfolio and integrated contact forms.",
        urlLink: "/portfolio/elektroteam",
        tags: ["web"],
    },
    {
        _id: 5,
        mainImage: "/images/portfolio/volton.jpg",
        title: "Volton-install.pl - Energy Corporation",
        metadata: "Corporate platform with CMS integration and comprehensive information modules.",
        urlLink: "/portfolio/volton",
        tags: ["web"],
    },
    {
        _id: 6,
        mainImage: "/images/portfolio/klicious-full.png",
        title: "Klicious - E-commerce Platform",
        metadata: "Online store with payment gateway integration and SEO-optimized product catalog.",
        urlLink: "/portfolio/klicious",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 7,
        mainImage: "/images/portfolio/skin.jpg",
        title: "SkinProjectClinic.pl - Beauty Clinic",
        metadata: "Service-oriented website with photo gallery and social media integration.",
        urlLink: "/portfolio/skinproject",
        tags: ["web"],
    },
    {
        _id: 8,
        mainImage: "/images/portfolio/slovlydeskop.jpg",
        title: "Slovly - E-commerce Store",
        metadata: "Online marketplace with advanced product search, filtering, and SEO optimization.",
        urlLink: "/portfolio/slovly",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 9,
        mainImage: "/images/portfolio/bakaliovelove.jpg",
        title: "BakalioweLove - Food E-commerce",
        metadata: "Specialty food store with online payments and responsive product pages.",
        urlLink: "/portfolio/bakaliowelove",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 10,
        mainImage: "/images/portfolio/paintball.jpg",
        title: "Paintball Osada - Recreation Park",
        metadata: "Entertainment venue website with package information, pricing, and location map.",
        urlLink: "/portfolio/paintball-osada",
        tags: ["web"],
    },
    // {
    //     _id: 9,
    //     mainImage: "/images/portfolio/smp.jpg",
    //     title: "SMP - Industrial Company",
    //     metadata: "Industrial services website with catalog integration and contact form functionality.",
    //     urlLink: "/portfolio/smpolaniec",
    //     tags: ["web"],
    // },
    {
        _id: 11,
        mainImage: "/images/portfolio/cora.jpg",
        title: "Cora Góralczyk - Handcraft E-commerce",
        metadata: "Artisan products store with payment integration and SEO-ready order management.",
        urlLink: "/portfolio/cora-goralczyk",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 12,
        mainImage: "/images/portfolio/bodymedica.jpg",
        title: "BodyMedica - Medical Clinic Online",
        metadata: "Healthcare platform with appointment booking, service descriptions, and health blog.",
        urlLink: "/portfolio/bodymedica",
        tags: ["web"],
    },
    {
        _id: 13,
        mainImage: "/images/portfolio/lanelyya.jpg",
        title: "Lanelyya - Fashion E-commerce",
        metadata: "Clothing store with product catalog, shopping cart, and recommendation system.",
        urlLink: "/portfolio/lanelyya",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 14,
        mainImage: "/images/portfolio/n8nfrontendapp.png",
        title: "n8n Fullstack Chatbot Frontend",
        metadata: "Versatile chat interface designed for multiple n8n workflow integrations.",
        urlLink: "https://github.com/piotrmacai/",
        tags: ["automations", "ai", "vibe coding"],
    },
    {
        _id: 15,
        mainImage: "/images/portfolio/geminin8n.png",
        title: "Gemini Chatbot App - AI Agent",
        metadata: "AI-powered chatbot with n8n integration for automated responses and lead generation.",
        urlLink: "https://github.com/piotrmacai/Gemini-Chatbot-App",
        tags: ["automations", "ai", "agents", "apps"],
    },
    {
        _id: 16,
        mainImage: "/images/portfolio/vercelchat.png",
        title: "AinsiderChat.vercel.app - AI Chat Platform",
        metadata: "Web-based AI conversation app with multiple LLM integrations and multi-user support.",
        urlLink: "https://ainsiderchat.vercel.app/",
        tags: ["ai", "apps"],
    },
    {
        _id: 17,
        mainImage: "/images/portfolio/leadgenapp.png",
        title: "AI Lead Generator Application",
        metadata: "Intelligent lead generation platform for automated customer acquisition and conversion.",
        urlLink: "https://github.com/piotrmacai/",
        tags: ["web", "ai", "apps"],
    },
    {
        _id: 18,
        mainImage: "/images/portfolio/macaiStudio.jpg",
        title: "Macai AI Chatbot - Portfolio Assistant",
        metadata: "Dedicated customer service AI agent with automated response generation and web integration.",
        urlLink: "/portfolio/macai-chatbot",
        tags: ["ai"],
    },
    // {
    //     _id: 17,
    //     mainImage: "/images/portfolio/uprawaChatbot.jpg",
    //     title: "Garden Accessories - AI Chatbot",
    //     metadata: "AI agent for plant cultivation store automating customer service operations.",
    //     urlLink: "/portfolio/akcesoriadouprawy-chatbot",
    //     tags: ["ai", "agents"],
    // },
    // {
    //     _id: 18,
    //     mainImage: "/images/portfolio/hfassistants.jpg",
    //     title: "HuggingFace Assistants - AI Personal Assistants",
    //     metadata: "Suite of AI agents for various tasks with HuggingFace and workflow automation integration.",
    //     urlLink: "/portfolio/huggingface-assistants",
    //     tags: ["ai"],
    // },
    {
        _id: 19,
        mainImage: "/images/portfolio/librechat.png",
        title: "OpenWebUI Docker - AI Chat Application",
        metadata: "Full-stack AI chat app in Docker with easy installation and custom workflow integration.",
        urlLink: "https://github.com/piotrmacai/librechat-docker",
        tags: ["ai", "apps", "agents"],
    },
    {
        _id: 20,
        mainImage: "/images/portfolio/marketingreport.png",
        title: "360 Marketing Reports AI System",
        metadata: "complete solution do generate marketing reports with conversational AI Agent",
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/marketing-reports-system",
        tags: ["ai", "web", "agents", "n8n"],
    },
    {
        _id: 21,
        mainImage: "/images/portfolio/websiteseoaudit.png",
        title: "Complete SEO & AEO Audit App",
        metadata: "complete solution for creating SEO & AEO audit reports for websites",
        tags: ["ai", "web", "agents", "n8n"],
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/seo-audit-v1",
    },
    {
        _id: 22,
        mainImage: "/images/portfolio/voiceflow.png",
        title: "Ainsider.cloud - Voice AI Platform",
        metadata: "Voicebot development platform with Twilio and n8n integration for AI voice assistants.",
        urlLink: "https://ainsider.cloud",
        tags: ["ai", "agents"],
    },
    {
        _id: 23,
        mainImage: "/images/portfolio/voicebot2.jpg",
        title: "VoiceBot AI - Lead Generation Voice Agent",
        metadata: "Advanced voicebot with natural speech and CRM integration for automated phone support.",
        urlLink: "/voicebot",
        tags: ["ai", "agents"],
    },
    {
        _id: 24,
        mainImage: "/images/portfolio/vercelchat.png",
        title: "Eleven Labs Agents Starter - Multi-Agent App",
        metadata: "Starter application for building AI agents using Eleven Labs and LLM for customer service.",
        urlLink: "https://v0.app/chat/eleven-labs-agents-starter-xuyVdQFxPAE?ref=L4O3TN",
        tags: ["ai", "agents"],
    },
    {
        _id: 25,
        mainImage: "/images/portfolio/voicebot.jpg",
        title: "VoiceBot Driving School - AI Voice Assistant",
        metadata: "Automated voice agent for driving school operations with intelligent call handling.",
        urlLink: "/portfolio/voicebot-drivingschool",
        tags: ["ai", "agents"],
    },
    {
        _id: 26,
        mainImage: "/images/portfolio/ainsiderbot.png",
        title: "Ainsider.co - Web and Automation Studio",
        metadata: "Comprehensive web development and automation services platform.",
        urlLink: "https://ainsider.co",
        tags: ["ai", "web", "featured"],
    },
    {
        _id: 27,
        mainImage: "/images/portfolio/n8n-workflows.webp",
        title: "n8n Fullstack Chatbot System",
        metadata: "Custom chatbot interface integrating with n8n workflows for complex business automations.",
        urlLink: "https://github.com/piotrmacai/n8n/",
        tags: ["web", "ai", "featured", "automations"],
    },
    {
        _id: 28,
        mainImage: "/images/portfolio/AiProductDesigner.png",
        title: "Gemini Product Photo Studio",
        metadata: "AI-powered application for generating and editing product photos with advanced masking technology.",
        urlLink: "https://github.com/piotrmacai/Gemini-ProductPhotoStudio",
        tags: ["web", "ai", "visuals", "vibe coding", "automations"],
    },
    {
        _id: 29,
        mainImage: "/images/portfolio/git.jpg",
        title: "GitHub Portfolio - PiotrMacai",
        metadata: "Open-source projects including apps, websites, agents, and automation solutions.",
        urlLink: "https://github.com/piotrmacai",
        tags: ["web", "ai", "featured"],
    },
    {
        _id: 30,
        mainImage: "/images/portfolio/design.jpg",
        title: "Behance Portfolio - Macai Studio",
        metadata: "Professional design work, visual content, and creative projects showcase.",
        urlLink: "https://www.behance.net/macaistudio",
        tags: ["web", "visuals", "featured"],
    },
    {
        _id: 31,
        mainImage: "/images/portfolio/videoautomation.jpg",
        title: "AI Video Generation & Publishing Automation",
        metadata: "Complete automation system for creating and distributing marketing videos to social media.",
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/ai-video-automation",
        tags: ["ai", "visuals", "automations"],
    },
    {
        _id: 32,
        mainImage: "/images/portfolio/creativeai.png",
        title: "AI Virtual Try-On Application",
        metadata: "Real-time image generation app with iterative editing using Nano Banana model.",
        urlLink: "https://github.com/piotrmacai/ai-virtual-tryon",
        tags: ["web", "ai", "visuals", "vibe coding", "featured"],
    },
    {
        _id: 33,
        mainImage: "/images/portfolio/elevenvercel.png",
        title: "Voice Agent Starter Kit",
        metadata: "Development toolkit using Vercel AI SDK and ElevenLabs for interactive voice AI applications.",
        urlLink: "https://github.com/piotrmacai/voice-agent-starter",
        tags: ["web", "ai", "vibe coding", "voice ai"],
    },
    {
        _id: 34,
        mainImage: "/images/portfolio/voicebotmacai.png",
        title: "Ainsider.store - Enterprise AI Voice Agent",
        metadata: "Custom-trained AI voice agent with proprietary business data for seamless website integration.",
        urlLink: "https://ainsider.store",
        tags: ["voice ai", "ai"],
    },
    {
        _id: 35,
        mainImage: "/images/portfolio/oskmachowski.jpg",
        title: "Oskmachowski.pl - Driving School Platform",
        metadata: "High-performance business website with SEO optimization and custom AI assistant integration.",
        urlLink: "https://oskmachowski.pl",
        tags: ["web", "ai", "featured"],
    },
    {
        _id: 36,
        mainImage: "/images/portfolio/ainsiderlink.jpg",
        title: "Ainsider.link - Custom Linktree with AI",
        metadata: "Next.js-powered Linktree alternative featuring integrated AI chatbot functionality.",
        urlLink: "https://ainsider.link",
        tags: ["web", "ai"],
    },
    {
        _id: 37,
        mainImage: "/images/portfolio/landingcrm.jpg",
        title: "Business CRM Landing Page",
        metadata: "Ultra-fast React.js landing page designed for modern SaaS platforms.",
        urlLink: "https://ai.studio/apps/drive/1gj3DyNXi5-9fgxTmBWZ_OH9cvNEqRVBR",
        tags: ["web", "vibe coding"],
    },
    {
        _id: 38,
        mainImage: "/images/portfolio/n8n-wordpress.png",
        title: "WordPress Blog Automation System",
        metadata: "Complete n8n automation for WordPress blog management from content generation to publishing.",
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/wordpress-full-blog-automation",
        tags: ["ai", "web", "automations"],
    },
    {
        _id: 39,
        mainImage: "/images/portfolio/rekrutspark.jpg",
        title: "RekrutSpark.com - HR Agency Platform",
        metadata: "Professional recruitment platform with custom CRM for efficient applicant management.",
        urlLink: "https://rekrutspark.com",
        tags: ["web"],
    },
    {
        _id: 40,
        mainImage: "/images/portfolio/crmnotion.png",
        title: "Ainsider.co/crm - Business CRM & Automation",
        metadata: "Personalized CRM system with integrated AI assistant and automated client workflows.",
        urlLink: "https://ainsider.co/crm",
        tags: ["web", "ai", "personal"],
    },
    {
        _id: 41,
        mainImage: "/images/portfolio/afterrave.jpg",
        title: "After-rave.eu - Supplement E-commerce",
        metadata: "Multilingual Shopify e-commerce platform for specialized supplement products.",
        urlLink: "https://after-rave.eu",
        tags: ["web", "ecommerce"],
    },
];

export default WebsitesData;
