import { Portfolio } from "@/types/portfolio";
import { useTranslation } from 'react-i18next';

const WebsitesData: Portfolio[] = [
    {
        _id: 1,
        mainImage: "/images/portfolio/ainsiderstorenew.png",
        title: "Ainsider.cloud - AI Tools and Prompts Directory",
        metadata: "A comprehensive directory for discovering the best AI tools and high-quality prompts to optimize your workflows.",
        urlLink: "https://ainsider.cloud",
        tags: ["web", "apps", "ai", "featured"],
    },
    {
        _id: 2,
        mainImage: "/images/portfolio/macailabs.png",
        title: "Personal Modern Dev Portfolio Website",
        metadata: "A modern portfolio website built with Next.js and Tailwind CSS.",
        urlLink: "https://macai.dev",
        tags: ["web", "apps", "ai", "featured"],
    },
    {
        _id: 3,
        mainImage: "/images/portfolio/omnibot.png",
        title: "n8n Fullstack Chatbot Frontend",
        metadata: "Versatile chat interface designed for multiple n8n workflow integrations.",
        urlLink: "https://omnichat.macai.dev",
        tags: ["automations", "ai", "vibe coding", "featured"],
    },
    {
        _id: 4,
        mainImage: "/images/portfolio/machtrans-full.png",
        title: "MachTrans.pl - Transport Company",
        metadata: "Responsive corporate website with full CMS integration and optimized performance.",
        urlLink: "https://machtrans.pl/",
        tags: ["web"],
    },
    {
        _id: 5,
        mainImage: "/images/portfolio/promptgallery.png",
        title: "Promptr Gallery - AI Art Prompts Directory",
        metadata: "An interactive gallery of AI art prompts with a unique feature to customize and refine them for your own creative projects.",
        urlLink: "https://gallery.ainsider.co",
        tags: ["web", "apps", "ai", "featured"],
    },
    {
        _id: 6,
        mainImage: "/images/portfolio/link-macai-dev.png",
        title: "Macai Link - Custom Linktree with AI",
        metadata: "Next.js-powered Linktree alternative featuring integrated AI chatbot functionality.",
        urlLink: "https://link.macai.dev",
        tags: ["web", "ai", "featured"],
    },
    {
        _id: 7,
        mainImage: "/images/portfolio/pgr-full.png",
        title: "PGR-Elektroteam.pl - Electrical Services",
        metadata: "Professional business website with project portfolio and integrated contact forms.",
        urlLink: "https://pgr-elektroteam.pl/",
        tags: ["web"],
    },
    {
        _id: 8,
        mainImage: "/images/portfolio/volton.jpg",
        title: "Volton-install.pl - Energy Corporation",
        metadata: "Corporate platform with CMS integration and comprehensive information modules.",
        urlLink: "https://voltoninstall.pl/",
        tags: ["web"],
    },
    {
        _id: 9,
        mainImage: "/images/portfolio/openwebui.png",
        title: "OpenWebUI Docker - AI Chat Application",
        metadata: "Full-stack AI chat app in Docker with easy installation and custom workflow integration.",
        urlLink: "https://github.com/piotrmacai/librechat-docker",
        tags: ["ai", "apps", "agents", "featured"],
    },
    {
        _id: 10,
        mainImage: "/images/portfolio/klicious-full.png",
        title: "Klicious - E-commerce Platform",
        metadata: "Online store with payment gateway integration and SEO-optimized product catalog.",
        urlLink: "https://k-licious.pl/",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 11,
        mainImage: "/images/portfolio/telegramagent.png",
        title: "Personal AI Assistant at Telegram",
        metadata: "Hackable custom personal AI assistant created at n8n and deployed/working from Telegram.",
        urlLink: "https://github.com/piotrmacai/librechat-docker",
        tags: ["ai", "apps", "agents", "n8n", "featured"],
    },
    {
        _id: 12,
        mainImage: "/images/portfolio/skin.jpg",
        title: "SkinProjectClinic.pl - Beauty Clinic",
        metadata: "Service-oriented website with photo gallery and social media integration.",
        urlLink: "https://www.skinprojectclinic.pl/",
        tags: ["web"],
    },
    {
        _id: 13,
        mainImage: "/images/portfolio/afterrave.jpg",
        title: "After-rave.eu - Supplement E-commerce",
        metadata: "Multilingual Shopify e-commerce platform for specialized supplement products.",
        urlLink: "https://after-rave.eu",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 14,
        mainImage: "/images/portfolio/slovlydeskop.jpg",
        title: "Slovly - E-commerce Store",
        metadata: "Online marketplace with advanced product search, filtering, and SEO optimization.",
        urlLink: "https://slovlystudio.com/",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 15,
        mainImage: "/images/portfolio/bakaliovelove.jpg",
        title: "BakalioweLove - Food E-commerce",
        metadata: "Specialty food store with online payments and responsive product pages.",
        urlLink: "https://bakaliowelove.pl/",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 16,
        mainImage: "/images/portfolio/geminin8n.png",
        title: "Gemini Chatbot App - AI Agent",
        metadata: "AI-powered chatbot with n8n integration for automated responses and lead generation.",
        urlLink: "https://github.com/piotrmacai/Gemini-Chatbot-App",
        tags: ["automations", "ai", "agents", "apps"],
    },
    {
        _id: 17,
        mainImage: "/images/portfolio/paintball.jpg",
        title: "Paintball Osada - Recreation Park",
        metadata: "Entertainment venue website with package information, pricing, and location map.",
        urlLink: "https://paintball-osada.pl/",
        tags: ["web"],
    },
    {
        _id: 18,
        mainImage: "/images/portfolio/cora.jpg",
        title: "Cora Góralczyk - Handcraft E-commerce",
        metadata: "Artisan products store with payment integration and SEO-ready order management.",
        urlLink: "https://cora-goralczyk.pl/",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 19,
        mainImage: "/images/portfolio/bodymedica.jpg",
        title: "BodyMedica - Medical Clinic Online",
        metadata: "Healthcare platform with appointment booking, service descriptions, and health blog.",
        urlLink: "https://bodymedica.pl/",
        tags: ["web"],
    },
    {
        _id: 20,
        mainImage: "/images/portfolio/lanelyya.jpg",
        title: "Lanelyya - Fashion E-commerce",
        metadata: "Clothing store with product catalog, shopping cart, and recommendation system.",
        urlLink: "https://lanellya.de",
        tags: ["web", "ecommerce"],
    },
    {
        _id: 21,
        mainImage: "/images/portfolio/leadgenapp.png",
        title: "AI Lead Generator Application",
        metadata: "Intelligent lead generation platform for automated customer acquisition and conversion.",
        urlLink: "https://github.com/piotrmacai/",
        tags: ["web", "ai", "apps"],
    },
    {
        _id: 22,
        mainImage: "/images/portfolio/macaiStudio.jpg",
        title: "Macai AI Chatbot - Portfolio Assistant",
        metadata: "Dedicated customer service AI agent with automated response generation and web integration.",
        urlLink: "/portfolio/macai-chatbot",
        tags: ["ai"],
    },
    {
        _id: 23,
        mainImage: "/images/portfolio/marketingreport.png",
        title: "360 Marketing Reports AI System",
        metadata: "complete solution do generate marketing reports with conversational AI Agent",
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/marketing-reports-system",
        tags: ["ai", "agents", "n8n"],
    },
    {
        _id: 24,
        mainImage: "/images/portfolio/websiteseoaudit.png",
        title: "Complete SEO & AEO Audit App",
        metadata: "complete solution for creating SEO & AEO audit reports for websites",
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/seo-audit-v1",
        tags: ["ai", "agents", "n8n"],
    },
    {
        _id: 25,
        mainImage: "/images/portfolio/voicebot2.jpg",
        title: "VoiceBot AI - Lead Generation Voice Agent",
        metadata: "Advanced voicebot with natural speech and CRM integration for automated phone support.",
        urlLink: "/voicebot",
        tags: ["ai", "agents"],
    },
    {
        _id: 26,
        mainImage: "/images/portfolio/voicebot.jpg",
        title: "VoiceBot Driving School - AI Voice Assistant",
        metadata: "Automated voice agent for driving school operations with intelligent call handling.",
        urlLink: "/portfolio/voicebot-drivingschool",
        tags: ["ai", "agents"],
    },
    {
        _id: 27,
        mainImage: "/images/portfolio/n8n.jpg",
        title: "n8n Fullstack Chatbot System",
        metadata: "Custom chatbot interface integrating with n8n workflows for complex business automations.",
        urlLink: "https://github.com/piotrmacai/n8n/",
        tags: ["web", "ai", "featured", "automations"],
    },
    {
        _id: 28,
        mainImage: "/images/portfolio/AiProductDesigner.png",
        title: "Gemini Product Photo Studio",
        metadata: "AI-powered application for generating and editing product photos with advanced masking technology.",
        urlLink: "https://github.com/piotrmacai/Gemini-ProductPhotoStudio",
        tags: ["web", "ai", "visuals", "vibe coding", "automations"],
    },
    {
        _id: 29,
        mainImage: "/images/portfolio/git.jpg",
        title: "GitHub Portfolio - PiotrMacai",
        metadata: "Open-source projects including apps, websites, agents, and automation solutions.",
        urlLink: "https://github.com/piotrmacai",
        tags: ["web", "ai", "featured"],
    },
    {
        _id: 30,
        mainImage: "/images/portfolio/design.jpg",
        title: "Behance Portfolio - Macai Studio",
        metadata: "Professional design work, visual content, and creative projects showcase.",
        urlLink: "https://www.behance.net/macaistudio",
        tags: ["web", "visuals", "featured"],
    },
    {
        _id: 31,
        mainImage: "/images/portfolio/videoautomation.jpg",
        title: "AI Video Generation & Publishing Automation",
        metadata: "Complete automation system for creating and distributing marketing videos to social media.",
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/ai-video-automation",
        tags: ["ai", "visuals", "automations"],
    },
    {
        _id: 32,
        mainImage: "/images/portfolio/creativeai.png",
        title: "AI Virtual Try-On Application",
        metadata: "Real-time image generation app with iterative editing using Nano Banana model.",
        urlLink: "https://github.com/piotrmacai/ai-virtual-tryon",
        tags: ["web", "ai", "visuals", "vibe coding", "featured"],
    },
    {
        _id: 33,
        mainImage: "/images/portfolio/voicebotmacai.png",
        title: "Customer support AI Voice Agent",
        metadata: "Custom-trained AI voice agent with proprietary business data for seamless website integration.",
        urlLink: "https://macai.dev",
        tags: ["agents", "ai"],
    },
    {
        _id: 34,
        mainImage: "/images/portfolio/oskmachowski.jpg",
        title: "Oskmachowski.pl - Driving School Platform",
        metadata: "High-performance business website with SEO optimization and custom AI assistant integration.",
        urlLink: "https://oskmachowski.pl",
        tags: ["web", "ai", "featured"],
    },
    {
        _id: 35,
        mainImage: "/images/portfolio/n8n-wordpress.png",
        title: "WordPress Blog Automation System",
        metadata: "Complete n8n automation for WordPress blog management from content generation to publishing.",
        urlLink: "https://github.com/piotrmacai/n8n/tree/main/wordpress-full-blog-automation",
        tags: ["ai", "web", "automations"],
    },
    {
        _id: 36,
        mainImage: "/images/portfolio/rekrutspark.jpg",
        title: "RekrutSpark.com - HR Agency Platform",
        metadata: "Professional recruitment platform with custom CRM for efficient applicant management.",
        urlLink: "https://rekrutspark.com",
        tags: ["web"],
    },
    {
        _id: 37,
        mainImage: "/images/portfolio/smp.jpg",
        title: "SMP - Industrial Company",
        metadata: "Industrial services website with catalog integration and contact form functionality.",
        urlLink: "/portfolio/smpolaniec",
        tags: ["web"],
    },
];

export default WebsitesData;
